[package]
name = "idsp"
version = "0.8.6"
resolver = "2"
edition = "2018"
authors = ["Robert Jördens <rj@quartiq.de>"]
license = "MIT OR Apache-2.0"
description = "DSP algorithms for embedded, mostly integer math"
homepage = "https://github.com/quartiq/idsp"
repository = "https://github.com/quartiq/idsp.git"
documentation = "https://docs.rs/idsp"

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
num-complex = { version = "0.4.0", features = ["serde"], default-features = false }
miniconf = "0.5"
num-traits = { version = "0.2.14", features = ["libm"], default-features = false}
libm = "0.2.5"

[dev-dependencies]
easybench = "1.0"
rand = "0.8"
ndarray = "0.15"

[[bench]]
name = "micro"
harness = false
